#!/bin/sh -eu
old_version="$1"
new_version="$2"
sed -i Cargo.toml -e "s/version = \"$old_version\"/version = \"$new_version\""

exit 1
git add Cargo.toml
git commit -m "Update version to $new_version"
