version: "3.8"
services:
  main:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ".:/usr/src/app"
    ports:
      - "3000:80"
    env_file: .env
    environment:
      HACKSTEAD_PRICE: "5"
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      LOCAL_DB: "true"

  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: "adorpheus"
      POSTGRES_USER: "farquit"
      POSTGRES_DB: "testagotchi"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
  ngrok:
    image: wernight/ngrok
    env_file: .ngrok.env
    environment:
      NGROK_PORT: main:80
    ports:
      - "3001:4040"
